apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxapp
spec:
  selector:
    matchLabels:
      app: nginxapp
  template:
    metadata:
      labels:
        app: nginxapp
    spec:
      containers:
      - name: nginxapp
        image: demisto/flask-nginx:1.0.0.2027021
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
