apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins_deploy
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:latest-jdk17
        resources:
          limits:
            memory: "4096Mi"
            cpu: "5000m"
        ports:
        - containerPort: 8080
